Repository GDSC-SKHU/2023-DontWorry-SolutionChallenge, pull requests merged in 2023-04, with the labels that each got.

#125 [#100] Search component
  src/components/Search/index.tsx
  src/pages/Report/index.tsx
Labels: feat

#128 [#95] Law api
  src/components/Law/LawContent.tsx
  src/components/Nav/Hamburger.tsx
  src/components/SelectCountry/index.tsx
  src/constants/lawData.ts
  src/hooks/api/useGetLaw.ts
  src/pages/DontWorry/Help/[countryName].tsx
  src/pages/DontWorry/Law/[countryName].tsx
  src/pages/DontWorry/Law/index.tsx
  src/remotes/law.d.ts
Labels: feat

#124 [#123] fix Write page Images upload
  src/pages/Main/Detail/[id].tsx
  src/pages/Main/Write.tsx
Labels: feat, fix

#130 [#129] Global Fonts Apply Error
  src/pages/_document.tsx
Labels: fix

#131 [#127] add ImageFolderDetailPhoto
  src/components/ImageDetail/index.tsx
  src/components/ImageFOL/index.tsx
  src/hooks/api/useGetImageFolderDetail.ts
  src/pages/ImageFolder/Detail/PhotoDetail/index.tsx
Labels: feat, fix
