Repository GDSC-SKHU/2023-DontWorry-SolutionChallenge, pull requests merged in 2023-02, with the labels that each got.

#4 [#3] apply theme style, type
  src/pages/_app.tsx
  styles/GlobalStyle.tsx
  styles/Theme/styled.d.ts
  styles/Theme/theme.ts
Labels: style

#8 [#6] main page style
  next.config.js
  public/images/food.jpg
  src/components/Nav/index.tsx
  src/components/Timeline/index.tsx
  src/pages/Main/Detail/[id].tsx
  src/pages/Main/index.tsx
  src/pages/_app.tsx
  styles/GlobalStyle.tsx
  styles/Theme/theme.ts
Labels: style

#15 [#7] communal BottomNav
  next.config.js
  package-lock.json
  package.json
  src/components/BottomNav/index.tsx
Labels: feat

#13 [#12] detail page style
  src/components/Common/Tag/index.tsx
  src/pages/Main/Detail/[id].tsx
Labels: style

#23 [#16] fix BottomNav
  src/components/BottomNav/index.tsx
Labels: fix

#11 [#10] optimize user experience
  LICENSE
  package-lock.json
  package.json
  src/@types/global.d.ts
  src/@types/styled.d.ts
  src/hooks/useTrackingPage.ts
  src/libs/analytics/gtag.ts
  src/libs/mixpanel/mixpanel.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
Labels: env

#20 [#19] Communal FormInput
  src/components/FormInput/index.tsx
Labels: feat

#26 [#22] framer-motion
  package-lock.json
  package.json
  src/components/Timeline/index.tsx
  src/constants/motion.ts
Labels: feat

#28 [#21] Communal Submit Button
  src/components/SubmitBtn/index.tsx
Labels: question, feat

#34 [#31] Communal Hamburger Menu
  src/components/BottomNav/index.tsx
  src/components/Nav/BottomNav.tsx
  src/components/Nav/Hamburger.tsx
  src/components/Nav/index.tsx
  src/pages/Main/index.tsx
Labels: feat, style

#33 [#18] About page
  public/images/aboutHands.jpg
  public/images/aboutHelpWomen.jpg
  public/images/aboutRaisingHands.jpg
  src/components/About/HrSummary.tsx
  src/constants/aboutFourKeyword.ts
  src/constants/motion.ts
  src/pages/DontWorry/About/index.tsx
Labels: feat, style

#36 [#35] pdf conversion
  package-lock.json
  package.json
  src/components/Common/Tag/index.tsx
  src/components/Pdf/MakePdf.tsx
  src/pages/Main/Detail/[id].tsx
Labels: feat

#39 [#38] useScroll
  src/components/Nav/BottomNav.tsx
  src/hooks/useScroll.ts
Labels: feat

#40 [#17] ImageFolderPage
  src/components/ImageFOL/index.tsx
  src/pages/ImageFolder/Detail/index.tsx
  src/pages/ImageFolder/index.tsx
Labels: feat

#37 [#27] Signup Component
  package-lock.json
  package.json
  src/components/FormInput/index.tsx
  src/constants/apiUrl.ts
  src/pages/Signin/index.tsx
  src/pages/Signup/index.tsx
Labels: feat

#42 [#41] Reduce framer-motion bundle size
  src/components/About/HrSummary.tsx
  src/components/ImageFOL/index.tsx
  src/components/Timeline/index.tsx
  src/pages/DontWorry/About/index.tsx
  src/pages/Main/index.tsx
  src/pages/_app.tsx
Labels: feat

#46 [#45] Communal: Modify Navbar
  src/components/Nav/Hamburger.tsx
  src/components/Nav/index.tsx
  src/pages/Main/index.tsx
Labels: feat, style

#51 [#49] Prettier, ESLint
  .eslintrc.json
  .prettierrc.json
  .vscode/settings.json
  package-lock.json
  package.json
  src/@types/styled.d.ts
  src/components/FormInput/index.tsx
  src/components/ImageFOL/index.tsx
  src/components/Nav/index.tsx
  src/components/Pdf/MakePdf.tsx
  src/components/Timeline/index.tsx
  src/hooks/useTrackingPage.ts
  src/pages/DontWorry/About/index.tsx
  src/pages/ImageFolder/Detail/index.tsx
  src/pages/ImageFolder/index.tsx
  src/pages/Main/index.tsx
  src/pages/Signup/index.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
Labels: feat

#53 [#52] Refactoring
  src/components/Common/Tag/index.tsx
  src/components/FormInput/index.tsx
  src/components/ImageFOL/index.tsx
  src/components/Nav/BottomNav.tsx
  src/components/Nav/Hamburger.tsx
  src/components/SubmitBtn/index.tsx
  src/components/Timeline/index.tsx
  src/hooks/useWindowSize.ts
  src/pages/DontWorry/About/index.tsx
  src/pages/DontWorry/Case/index.tsx
  src/pages/DontWorry/Law/index.tsx
  src/pages/ImageFolder/Detail/index.tsx
  src/pages/ImageFolder/index.tsx
  src/pages/Main/Detail/[id].tsx
  src/pages/index.tsx
Labels: feat, env

#55 [#54] main page toggle
  src/pages/Main/index.tsx
Labels: feat, style
