Repository GDSC-SKHU/2023-DontWorry-SolutionChallenge, pull requests merged in 2023-03, with the labels that each got.

#56 [#50] Communal Modal
  package-lock.json
  src/components/Modal/index.tsx
Labels: feat

#58 [#44] Help Page
  src/components/Nav/Hamburger.tsx
  src/pages/DontWorry/Help/index.tsx
  styles/Theme/theme.ts
Labels: feat

#60 [#32] Write page
  src/components/Write/Form/FormDate.tsx
  src/components/Write/Form/FormImages.tsx
  src/components/Write/Form/FormLocation.tsx
  src/components/Write/Form/FormSummary.tsx
  src/components/Write/Form/FormTag.tsx
  src/components/Write/Form/FormTitle.tsx
  src/components/Write/Form/FormVideo.tsx
  src/components/Write/ImageUpload.tsx
  src/components/Write/Input.tsx
  src/components/Write/TextArea.tsx
  src/components/Write/Title.tsx
  src/components/Write/VideoUpload.tsx
  src/constants/writeExplain.ts
  src/pages/Main/Write.tsx
Labels: feat

#64 Fix for deploy
  package-lock.json
  package.json
  src/components/ImageDetail/index.tsx
Labels: fix

#69 [#65] favicon
  public/favicon.ico
Labels: feat

#70 [#68] Optimization styled-components
  .babelrc
  package-lock.json
  package.json
  src/pages/_document.js
  tsconfig.json
Labels: fix

#73 [#67] Fix Modal
  src/components/Modal/index.tsx
Labels: fix

#71 [#29] Login Component
  package-lock.json
  package.json
  src/components/Login/index.tsx
  src/constants/apiUrl.ts
  src/constants/appClient.ts
  src/constants/firebaseConfig.ts
  src/constants/firebaseUrl.ts
  src/pages/Signin/index.tsx
  src/pages/Signup/index.tsx
Labels: feat

#75 [#66] Law Page
  src/constants/lawData.ts
  src/pages/DontWorry/Law/index.tsx
  styles/Theme/theme.ts
Labels: feat

#76 [#72] Main page
  package-lock.json
  package.json
  public/images/mainCounsel.jpg
  public/images/mainKids.jpg
  public/images/mainNoSilence.jpg
  src/components/Carousel/index.tsx
  src/components/Common/Balloon/ReportBalloon.tsx
  src/components/Common/Button/ReportBtn/index.tsx
  src/components/Common/Text/MainMsg.tsx
  src/components/Modal/index.tsx
  src/pages/Main/index.tsx
  src/pages/Report/index.tsx
  src/pages/_document.js
  src/pages/_document.tsx
  tsconfig.json
Labels: feat

#78 fix package,package-lock.json
  package-lock.json
  package.json
Labels: fix

#84 [#83] fix deploy, package
  package-lock.json
  src/pages/Signin/index.tsx
Labels: fix

#85 [#82] apply main api
  src/components/Timeline/index.tsx
  src/hooks/api/useGetMain.ts
  src/pages/Report/index.tsx
  src/remotes/main.d.ts
Labels: feat

#87 [#86] Apply help api to selectCoutry component
  src/components/Nav/Hamburger.tsx
  src/components/SelectCountry/index.tsx
  src/hooks/api/useGetHelp.ts
  src/pages/DontWorry/Help/[countryName].tsx
  tsconfig.json
Labels: feat

#90 [#89] Main api user connection
  next.config.js
  src/components/Timeline/index.tsx
  src/pages/Main/index.tsx
  src/pages/Report/index.tsx
Labels: feat

#92 [#91] Check if logged in
  src/components/Nav/Hamburger.tsx
  src/pages/DontWorry/About/index.tsx
  src/pages/Signin/index.tsx
  src/pages/index.tsx
Labels: feat

#97 [#94] apply custom404Page
  src/assets/lottieJSON/404.json
  src/pages/404/index.tsx
Labels: feat

#101 [#9] write page submit form
  package-lock.json
  package.json
  src/components/Write/Form/FormDate.tsx
  src/components/Write/Form/FormImages.tsx
  src/components/Write/Form/FormLocation.tsx
  src/components/Write/Form/FormSummary.tsx
  src/components/Write/Form/FormTag.tsx
  src/components/Write/Form/FormTitle.tsx
  src/components/Write/ImageUpload.tsx
  src/components/Write/Input.tsx
  src/components/Write/TextArea.tsx
  src/constants/appClient.ts
  src/pages/Main/Write.tsx
  src/pages/_app.tsx
  src/remotes/photo.d.ts
  src/remotes/upload.d.ts
Labels: feat

#103 [#102] delete getServerSideProps
  src/pages/ImageFolder/Detail/index.tsx
  src/pages/ImageFolder/index.tsx
  src/pages/Report/index.tsx
  src/pages/Signin/index.tsx
  src/pages/Signup/index.tsx
  src/pages/_app.tsx
Labels: feat, env

#105 [#104] Fix CasePage
  src/assets/lottieJSON/construction.json
  src/pages/404/index.tsx
  src/pages/DontWorry/Case/index.tsx
Labels: feat, fix

#107 [#88] Detail api
  src/components/Timeline/index.tsx
  src/hooks/api/useGetMainById.ts
  src/pages/Main/Detail/[id].tsx
  src/pages/Report/index.tsx
  src/remotes/main.d.ts
  src/remotes/mainDetail.d.ts
Labels: feat

#109 [#108]Add Modal- ImagesBtn
  package-lock.json
  src/components/Modal/index.tsx
  src/components/Nav/BottomNav.tsx
Labels: fix

#110 [#99] Main api Image
  src/components/Timeline/index.tsx
  src/components/Write/Form/FormImages.tsx
  src/components/Write/Form/FormTag.tsx
  src/components/Write/ImageUpload.tsx
  src/constants/writeExplain.ts
  src/pages/Main/Write.tsx
  src/pages/Report/index.tsx
Labels: feat

#111 [#106] Write page modal
  src/components/Timeline/index.tsx
  src/pages/Main/Detail/[id].tsx
  src/pages/Main/Write.tsx
Labels: feat, fix

#115 [#114] modify style
  src/pages/Main/Detail/[id].tsx
  src/pages/Main/Write.tsx
  src/pages/Main/index.tsx
Labels: style

#116 [#113] Write README
  README.md
Labels: env

#117 [#112] SIgnup Error Modal
  src/components/Modal/index.tsx
  src/pages/Signin/index.tsx
  src/pages/Signup/index.tsx
Labels: feat, fix

#122 [#121] modify README
  README.md
Labels: env
